### ISSUE TITLE
Dynamic Recipe Detail Page

### ISSUE THREAD

**Issue by Ken-Ngcobo** [CodeSpace-Academy/ASE_2024_GROUP_C#26]
As a developer, I want to create a dynamic recipe detail page so that users can view more information about a recipe when they click on it from the homepage.

Acceptance Criteria:
When a user clicks on a recipe card from the homepage, they are directed to the corresponding recipe detail page with a unique URL based on the recipe ID.

**Comment by SABELOMAWELA** [comment]
Wrapped RecipeCard component with Next.js Link component, adding navigation to recipe details page
