### ISSUE TITLE
Show Recipe Title and Description

### ISSUE THREAD

**Issue by Ken-Ngcobo** [CodeSpace-Academy/ASE_2024_GROUP_C#29]
As a developer, I want the recipe detail page to display the recipe title and description so that users can understand what the recipe entails.

Acceptance Criteria:
The recipe title and description are prominently displayed at the top of the recipe detail page.

**Comment by SABELOMAWELA** [comment]
This update enhances the recipe detail page by prominently displaying the recipe title and description. The recipe title is shown at the top of the page, followed by the recipe description (instructions) clearly displayed below it. The changes were made in the `RecipeDetail` component to ensure the title and description are fetched and rendered correctly from the API.
